### PR TITLE
ibuffer column function to display relative filenames when belonging …

### PR DESCRIPTION
**Pull request by paxperscientiam**
…to a project

Hey @purcell ,

The code isn't perfect, but it works! Let me know what you think.

screen shot 2018-10-09 at 2 16 15 am

EDIT: Note that I haven't done too much in the way of testing. This would be my first emacs package contribution.

### CODE REVIEW

**Comment by paxperscientiam** [comment]
Bump

**Comment by purcell** [comment]
Thanks for this. The change broadly makes sense, and I can see it would be useful! Firstly, though, the emoji should be removed, please -- I'm not going to field bug reports for when it doesn't show up, or when people want to know how to remove it.

Additionally, I think the `::/` prefix should be removed, so that the filename is simply a relative path from the project root, e.g. `resources/src/bs.css` in the example above. (You can do this with `file-relative-name path`, so no `dired` functions are necessary.)

**Comment by purcell** [comment]
(There would also need to be an `autoload`, as for the columns defined above.)

**Comment by purcell** [comment]
I took this and applied a modified version of the code, and also made `ibuffer-vc` (which I use in preference to this package) work the same way. Thanks!

**Pull request closed without merging**
